name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  # Required by golangci-lint action to create annotations on PRs.
  # https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#comments-and-annotations
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
      - name: Run go version
        run: go version
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Run node --version
        run: node --version
      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend
      - name: Lint Go
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56
      - name: Lint frontend
        run: make lint-frontend
      
