name: Test

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
      - name: Run go version
        run: go version
      - name: Create placeholder asset
        # go:embed requires the directory to exist and be non-empty
        run: |
          mkdir -p ./frontend/dist
          touch ./frontend/dist/placeholder
      - name: Run tests
        run: make test
